### PR TITLE
Add auto-fix for NoExposingEverything

### LINKED ISSUE #2: Have NoExposingEverything provide a fix
The following module definition would be reported

```elm
module A exposing (..)

type A = B | C
type alias D = {}
a = 1
```

We could have the rule provide an automatic fix that would replace `(..)`, like here:
```elm
module A exposing (A(..), D, a)
```

Ideally, the formatting would already look like something `elm-format` would produce, meaning types first in alphabetical order, then functions/values in alphabetical order. That would help the user see quite easily what is happening. I don't think it is useful to try and format in accordance to the `@docs`, since `elm-format` will re-format anyway.

# Proposed solution

We would need to add a [`declarationListVisitor`](https://package.elm-lang.org/packages/jfmengels/elm-review/latest/Review-Rule#withDeclarationListVisitor) that goes through all declarations and registers them.

Then, when we create the error, which we now need to do [in a final module evaluation](https://package.elm-lang.org/packages/jfmengels/elm-review/latest/Review-Rule#withFinalModuleEvaluation), we'd provide the fix.

### PR DESCRIPTION
**Pull request by sparksp**
Adds all declarations as the exposing list, in the order they appear. `elm-format` will reorganise them based on `@docs` or alphabetically.

Fixes #2

### CODE REVIEW

**Comment by sparksp** [comment]
Looks like the examples are out of sync with the preview - although I've not touched them with this PR. Happy to update them when the PR's approved.

File: src/NoExposingEverything.elm [hunk 1]
```diff
@@ -52,25 +56,80 @@ elm-review --template jfmengels/elm-review-common/example --rules NoExposingEver
 -}
 rule : Rule
 rule =
-    Rule.newModuleRuleSchema "NoExposingEverything" ()
-        |> Rule.withSimpleModuleDefinitionVisitor moduleDefinitionVisitor
+    Rule.newModuleRuleSchema "NoExposingEverything" ExposingUnknown
```
Comment (jfmengels) [inline src/NoExposingEverything.elm]: I feel like you could hardcode to `ExposingOk` to start with. `moduleDefinitionVisitor` will be called soon anyway.

**Review by jfmengels — COMMENTED** [review]
> Looks like the examples are out of sync with the preview - although I've not touched them with this PR. Happy to update them when the PR's approved.

Yeah, I think that's related to https://github.com/jfmengels/node-elm-review/issues/27

**Review by jfmengels — APPROVED** [review]
Awesome and quick work @sparksp :blush: 

Thanks a lot! :pray:
